-- AlterTable
ALTER TABLE `user` ADD COLUMN `companyId` INTEGER NULL,
    ADD COLUMN `role` VARCHAR(191) NOT NULL DEFAULT 'ADMIN';

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `Company`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
